### ISSUE TITLE
How to sign a transaction?

### ISSUE THREAD

**Issue by JellyBool** [Achse/geth-jsonrpc-php-client#2]
In the document I see ：

* sign transactions,
* deploy transactions,

But how to `sign transactions`?

**Comment by Achse** [comment]
Hey, whole code is pretty simple, just provide method and parameters. Parameters depends from what method you're using. For sign transaction see: https://github.com/ethereum/wiki/wiki/JSON-RPC#eth_sign

**Comment by Achse** [comment]
Its been a while I last use this lib. You can see how paramters are treated directly in the code here: https://github.com/Achse/geth-jsonrpc-php-client/blob/master/src/JsonRpc/Client.php#L52

**Comment by yogeshpadsala** [comment]
Hello Achse, thanks for this good library..

For eth_sign method, it says:  "Note the address to sign with must be unlocked."

Can anyone kindly tell me how I can unlock an account using un-encrypted private key?

Thanks in advance for any thoughts on this..
