### ISSUE TITLE
some methods won't work (bad json request)

### ISSUE THREAD

**Issue by sctt** [Achse/geth-jsonrpc-php-client#6]
hello,

i'm just trying to invoke eth_sendTransaction, but it fails with this error:
`invalid argument 0: json: cannot unmarshal string into Go value of type ethapi.SendTxArgs`

i noticed that your lib removes all array keys for sendTransaction params, that doesn't seem to comply with the official json rpc spec: https://github.com/ethereum/wiki/wiki/JSON-RPC#eth_sendtransaction

i worked around this with a little hack, and it works perfectly (no error, and the transaction is inserted correctly):

`
src/JsonRpc/Client.php:54

        public function callMethod($method, array $params)
        {

                if ($method == "eth_sendTransaction")
                        $request = [
                                'jsonrpc' => $this->jsonRpcVersion,
                                'method' => $method,
                                'params' => array($params),
                                'id' => $this->id,
                        ];
                else
                        $request = [
                                'jsonrpc' => $this->jsonRpcVersion,
                                'method' => $method,
                                'params' => array_values($params),
                                'id' => $this->id,
                        ];

                $body = Json::encode($request);
                $rawResponse = $this->client->post($body);
[...]

`

are you aware of this problem? is there a better solution?
thank you.

**Comment by Achse** [comment]
Hi, thanks for reporting it. 

I went through Doc and it appears to me that it works differently. I wonder that snippet provided by you is actually working. 

I went through API Doc and I have found that those `eth_sendTransaction`, `eth_newFilter`,  `eth_getLogs` and `shh_post` are indeed expecting object but as first argument of `"params"` array.

So in a code this like this:

```php
->callMethod('eth_sendTransaction', [[ // <-- here is associative array inside of normal array
    "from" => "0x04f96a5e25610293e42a73908e93ccc8c4d4dc0edcfa9fa872f50cb214e08ebf61a03e245533f97284d442460f2998cd41858798ddfd4d661997d3940272b717b1",
    "to" => "0x3e245533f97284d442460f2998cd41858798ddf04f96a5e25610293e42a73908e93ccc8c4d4dc0edcfa9fa872f50cb214e08ebf61a0d4d661997d3940272b717b1",
    "topics" => ["0x776869737065722d636861742d636c69656e74", "0x4d5a695276454c39425154466b61693532"],
    "payload" => "0x7b2274797065223a226d6",
    "priority" => "0x64",
    "ttl" => "0x64",
]]);
```
