### ISSUE TITLE
Making port optional?

### ISSUE THREAD

**Issue by kornrunner** [Achse/geth-jsonrpc-php-client#7]
Hi,

Would you consider making port optional, or supporting full URI's instead of host/IP + port combo?
I'm looking into using a QuikNode that has a JSON RPC exposed via some url like:

https://quiknode.io/blabla/blabla/

JSON RPC is exposed at given URL, there's no explicit port (implicit port is 443 due to https). `$port` param is mandatory, and whatever value is passed - it generates a bad url. So, perhaps we can ignore it if passed as `null`. And if set to `null`, then it wouldn't get `sprintf`'d here: https://github.com/Achse/geth-jsonrpc-php-client/blob/master/src/JsonRpc/GuzzleClient.php#L40

I can do a PR if you're okay with that change, or we can discuss some other solution.

Thanks!

**Comment by Achse** [comment]
merged

**Comment by Achse** [comment]
I have merged your pull request but also migrated project on PHP7.2 and allow for port to be optional.

**Comment by Achse** [comment]
see: https://github.com/Achse/geth-jsonrpc-php-client/pull/9

**Comment by Achse** [comment]
New version (BC Break): https://github.com/Achse/geth-jsonrpc-php-client/releases/tag/3.0.0
